In [1]:
#Instala la libreria PyODBC
!pip install pyodbc

Collecting pyodbc
  Downloading pyodbc-5.3.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.7 kB)
Downloading pyodbc-5.3.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (340 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 340.3/340.3 kB 13.1 MB/s eta 0:00:00
Installing collected packages: pyodbc
Successfully installed pyodbc-5.3.0

In [2]:
import pyodbc
import pandas as pd

In [3]:
# Instalar dependencias y repositorio de Microsoft
!sudo su -c "curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -"
!sudo su -c "curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list > /etc/apt/sources.list.d/mssql-release.list"
!sudo apt-get update
!sudo ACCEPT_EULA=Y apt-get install -y msodbcsql17 unixodbc-dev

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
100   975  100   975    0     0   4311      0 --:--:-- --:--:-- --:--:--  4314
OK
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    89  100    89    0     0    709      0 --:--:-- --:--:-- --:--:--   712
Get:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Get:2 https://cli.github.com/packages stable InRelease [3,917 B]
Get:3 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:4 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease [3,632 B]
Get:5 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Hit:6 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:8 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main arm64 Packages [108 kB]
Get:9 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main all Packages [1,331 B]
Get:10 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main armhf Packages [22.2 kB]
Get:11 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 Packages [282 kB]
Hit:12 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:13 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:14 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [2,860 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:16 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,287 kB]
Get:17 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [9,573 kB]
Get:18 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [3,633 kB]
Get:19 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [6,205 kB]
Get:20 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,598 kB]
Get:21 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [69.2 kB]
Get:22 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [6,411 kB]
Get:23 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [3,966 kB]
Get:24 http://archive.ubuntu.com/ubuntu jammy-backports/main amd64 Packages [83.9 kB]
Get:25 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [37.2 kB]
Fetched 36.5 MB in 7s (5,204 kB/s)
Reading package lists... Done
W: https://packages.microsoft.com/ubuntu/22.04/prod/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
unixodbc-dev is already the newest version (2.3.9-5ubuntu0.1).
unixodbc-dev set to manually installed.
The following additional packages will be installed:
  odbcinst unixodbc
The following NEW packages will be installed:
  msodbcsql17 odbcinst unixodbc
0 upgraded, 3 newly installed, 0 to remove and 6 not upgraded.
Need to get 783 kB of archives.
After this operation, 164 kB of additional disk space will be used.
Get:1 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 msodbcsql17 amd64 17.10.6.1-1 [746 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 odbcinst amd64 2.3.9-5ubuntu0.1 [9,930 B]
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 unixodbc amd64 2.3.9-5ubuntu0.1 [26.7 kB]
Fetched 783 kB in 1s (966 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 3.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package odbcinst.
(Reading database ... 117528 files and directories currently installed.)
Preparing to unpack .../odbcinst_2.3.9-5ubuntu0.1_amd64.deb ...
Unpacking odbcinst (2.3.9-5ubuntu0.1) ...
Selecting previously unselected package unixodbc.
Preparing to unpack .../unixodbc_2.3.9-5ubuntu0.1_amd64.deb ...
Unpacking unixodbc (2.3.9-5ubuntu0.1) ...
Selecting previously unselected package msodbcsql17.
Preparing to unpack .../msodbcsql17_17.10.6.1-1_amd64.deb ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78.)
debconf: falling back to frontend: Readline
Unpacking msodbcsql17 (17.10.6.1-1) ...
Setting up odbcinst (2.3.9-5ubuntu0.1) ...
Setting up unixodbc (2.3.9-5ubuntu0.1) ...
Setting up msodbcsql17 (17.10.6.1-1) ...
odbcinst: Driver installed. Usage count increased to 1.
    Target directory is /etc
Processing triggers for man-db (2.10.2-1) ...

In [6]:
import pyodbc

# Parámetros de conexión
server = 'cdsc-bit.database.windows.net'
database = 'BDPruebasBIT'
username = 'TestUser1'
password = 'Hola2025'
driver = '{ODBC Driver 17 for SQL Server}'
conn = pyodbc.connect(
    f'DRIVER={driver};SERVER={server};DATABASE={database};UID={username};PWD={password};Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;'
)
cur = conn.cursor()

### Vista general de todas las tablas actualmente existentes dentro de la base de datos

In [7]:
cur.execute("""
SELECT * FROM INFORMATION_SCHEMA.Tables
""")

for row in cur.fetchall():
  print(row)

('BDPruebasBIT', 'dbo', 'BuildVersion', 'BASE TABLE')
('BDPruebasBIT', 'dbo', 'ErrorLog', 'BASE TABLE')
('BDPruebasBIT', 'SalesLT', 'Address', 'BASE TABLE')
('BDPruebasBIT', 'SalesLT', 'CustomerAddress', 'BASE TABLE')
('BDPruebasBIT', 'SalesLT', 'SalesOrderDetail', 'BASE TABLE')
('BDPruebasBIT', 'SalesLT', 'SalesOrderHeader', 'BASE TABLE')
('BDPruebasBIT', 'sys', 'database_firewall_rules', 'VIEW')
('BDPruebasBIT', 'SalesLT', 'Customer', 'BASE TABLE')
('BDPruebasBIT', 'SalesLT', 'ProductModel', 'BASE TABLE')
('BDPruebasBIT', 'SalesLT', 'vProductModelCatalogDescription', 'VIEW')
('BDPruebasBIT', 'SalesLT', 'ProductDescription', 'BASE TABLE')
('BDPruebasBIT', 'SalesLT', 'Product', 'BASE TABLE')
('BDPruebasBIT', 'dbo', 'alumnos', 'BASE TABLE')
('BDPruebasBIT', 'SalesLT', 'ProductModelProductDescription', 'BASE TABLE')
('BDPruebasBIT', 'SalesLT', 'vProductAndDescription', 'VIEW')
('BDPruebasBIT', 'SalesLT', 'ProductCategory', 'BASE TABLE')
('BDPruebasBIT', 'SalesLT', 'vGetAllCategories', 'VIEW')

In [ ]:
# Consulta todos los registros
cur.execute('SELECT * FROM SalesLT.Customer')
for row in cur.fetchall():
    print(row)

In [10]:
df = pd.read_sql_query("SELECT * FROM SalesLT.Customer", conn)
df

/tmp/ipython-input-981501237.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("SELECT * FROM SalesLT.Customer", conn)

,CustomerID,NameStyle,Title,FirstName,MiddleName,LastName,Suffix,CompanyName,SalesPerson,EmailAddress,Phone,PasswordHash,PasswordSalt,rowguid,ModifiedDate
0,1,False,Mr.,Orlando,N.,Gee,None,A Bike Store,adventure-works\pamela0,orlando0@adventure-works.com,245-555-0173,L/Rlwxzp4w7RWmEgXX+/A7cXaePEPcp+KwQhl2fJL7w=,1KjXYs4=,3F5AE95E-B87D-4AED-95B4-C3797AFCB74F,2005-08-01
1,2,False,Mr.,Keith,None,Harris,None,Progressive Sports,adventure-works\david8,keith0@adventure-works.com,170-555-0127,YPdtRdvqeAhj6wyxEsFdshBDNXxkCXn+CRgbvJItknw=,fs1ZGhY=,E552F657-A9AF-4A7D-A645-C429D6E02491,2006-08-01
2,3,False,Ms.,Donna,F.,Carreras,None,Advanced Bike Components,adventure-works\jillian0,donna0@adventure-works.com,279-555-0130,LNoK27abGQo48gGue3EBV/UrlYSToV0/s87dCRV7uJk=,YTNH5Rw=,130774B1-DB21-4EF3-98C8-C104BCD6ED6D,2005-09-01
3,4,False,Ms.,Janet,M.,Gates,None,Modular Cycle Systems,adventure-works\jillian0,janet1@adventure-works.com,710-555-0173,ElzTpSNbUW1Ut+L5cWlfR7MF6nBZia8WpmGaQPjLOJA=,nm7D5e4=,FF862851-1DAA-4044-BE7C-3E85583C054D,2006-07-01
4,5,False,Mr.,Lucy,None,Harrington,None,Metropolitan Sports Supply,adventure-works\shu0,lucy0@adventure-works.com,828-555-0186,KJqV15wsX3PG8TS5GSddp6LFFVdd3CoRftZM/tP0+R4=,cNFKU4w=,83905BDC-6F5E-4F71-B162-C98DA069F38A,2006-09-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
842,30113,False,Mr.,Raja,D.,Venugopal,None,Nearby Cycle Shop,adventure-works\jae0,raja0@adventure-works.com,1 (11) 500 555-0195,lx5a4+AFGzH6mzjz6hpiR9scxbYGX8OcqFpv/cI6yFs=,hSwmBWk=,84975C44-DC82-49D3-BFC4-8F31B4C8E994,2006-09-01
843,30115,False,Ms.,Dora,P.,Verdad,None,Retreat Inn,adventure-works\josé1,dora0@adventure-works.com,155-555-0140,RgzxIE8hSY/z6iJnmDYMZWdJTQBRaWKI7UaZhAPhPxY=,jYD20wc=,E4CF8FD5-30A4-4B8E-8FD8-47032E255778,2006-08-01
844,30116,False,Ms.,Wanda,F.,Vernon,None,Technical Parts Manufacturing,adventure-works\shu0,wanda0@adventure-works.com,433-555-0168,hNQpZV8787KyeDWfllnZWzY+l8DFEYTnwoZZzYtusi0=,HDCU1Bk=,EC409609-D25D-41B8-9D15-A1AA6E89FC77,2007-07-01
845,30117,False,Mr.,Robert,R.,Vessa,None,Totes & Baskets Company,adventure-works\jillian0,robert13@adventure-works.com,560-555-0171,UWGC2U8F7AUNA2FuiT4agrBoxAFskHGQSxqP39B7zLQ=,iES3IZA=,6F08E2FB-1CD3-4F6E-A2E6-385669598B19,2005-08-01
846,30118,False,Ms.,Caroline,A.,Vicknair,None,World of Bikes,adventure-works\jillian0,caroline0@adventure-works.com,695-555-0158,U1/CrPqSzwLTtwgBehfpIl7f1LHSFpZw1qnG1sMzFjo=,QhHP+y8=,2495B4EB-FE8B-459E-A1B6-DBA25C04E626,2006-09-01

In [ ]:
conn.close()

# Crear una tabla

In [11]:
import pyodbc

# Parámetros de conexión
server = 'cdsc-bit.database.windows.net'
database = 'BDPruebasBIT'
username = 'DDLUser1'
password = 'Hola2025'
driver = '{ODBC Driver 17 for SQL Server}'
conn = pyodbc.connect(
    f'DRIVER={driver};SERVER={server};DATABASE={database};UID={username};PWD={password};Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;'
)
cur = conn.cursor()

In [15]:
cur.execute('''
CREATE TABLE alumnos (
    id INTEGER PRIMARY KEY IDENTITY(1,1),
    nombre VARCHAR(200),
    edad INTEGER,
    ciudad VARCHAR(200)
)
''')

In [14]:
cur.execute('''
DROP TABLE alumnos
''')

In [16]:
conn.commit()

## Ingresar datos

In [20]:
import pyodbc

# Parámetros de conexión
server = 'cdsc-bit.database.windows.net'
database = 'BDPruebasBIT'
username = 'WriterUser1'
password = 'Hola2025'
driver = '{ODBC Driver 17 for SQL Server}'
conn = pyodbc.connect(
    f'DRIVER={driver};SERVER={server};DATABASE={database};UID={username};PWD={password};Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;'
)
cur = conn.cursor()

In [23]:
alumnos = [
    ('Ana', 22, 'Bogotá'),
    ('Luis', 24, 'Medellín'),
    ('Marta', 23, 'Cali'),
    ('Pedro', 22, 'Bogotá')
]

cur.executemany('INSERT INTO alumnos VALUES ( ?, ?, ?)', alumnos)
conn.commit()

In [26]:
alumnos = [
    ('Cristian', 27, 'Bogotá'),
]

cur.executemany('INSERT INTO alumnos VALUES ( ?, ?, ?)', alumnos)
conn.commit()

In [ ]:
cur.execute('''

BEGIN TRANSACTION

UPDATE alumnos
SET edad = edad + 1
WHERE id = 5

ROLLBACK TRANSACTION

''')

In [ ]:
conn.commit()

In [ ]:
cur.execute('''
DELETE alumnos
''')

In [ ]:
conn.rollback()  ## Regresa a la ultima version (ultimo commit)

In [27]:
pd.read_sql_query("SELECT * FROM alumnos", conn)

/tmp/ipython-input-911934941.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM alumnos", conn)

   id    nombre  edad    ciudad
0   1       Ana    22    Bogotá
1   2      Luis    24  Medellín
2   3     Marta    23      Cali
3   4     Pedro    22    Bogotá
4   5  Cristian    27    Bogotá

In [28]:
# Consulta todos los registros
cur.execute('SELECT * FROM alumnos')
for row in cur.fetchall():
    print(row)

(1, 'Ana', 22, 'Bogotá')
(2, 'Luis', 24, 'Medellín')
(3, 'Marta', 23, 'Cali')
(4, 'Pedro', 22, 'Bogotá')
(5, 'Cristian', 27, 'Bogotá')

In [ ]:
conn.commit()

## Ingresar datos de un CSV

In [30]:
formulario = pd.read_csv('/content/Asistencia.csv')
formulario

                   Timestamp                     Nombre  Edad         Ciudad
0  2026/01/05 7:27:03 PM EST              Brayan posada    31         Bogota
1  2026/01/05 7:27:10 PM EST                      Joan     22         Bogotá
2  2026/01/05 7:27:10 PM EST  Diego Andres Paez Menjura    19  Villavicencio
3  2026/01/05 7:27:11 PM EST                     Danilo    32       Medellin
4  2026/01/05 7:27:19 PM EST             Faber Grisales    27         Bogotá
5  2026/01/05 7:27:25 PM EST                    MICHAEL    37         SOACHA

In [52]:
import pyodbc

# Parámetros de conexión
server = 'cdsc-bit.database.windows.net'
database = 'BDPruebasBIT'
username = 'WriterUser1'
password = 'Hola2025'
driver = '{ODBC Driver 17 for SQL Server}'
conn = pyodbc.connect(
    f'DRIVER={driver};SERVER={server};DATABASE={database};UID={username};PWD={password};Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;'
)
cur = conn.cursor()

In [33]:
for _, row in formulario.iterrows():
    cur.execute('INSERT INTO alumnos (nombre, edad, ciudad) VALUES (?, ?, ?)', (row['Nombre'], row['Edad'], row['Ciudad']))
conn.commit()

In [35]:
consulta = pd.read_sql_query("SELECT * FROM alumnos", conn)
consulta

/tmp/ipython-input-3685748699.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  consulta = pd.read_sql_query("SELECT * FROM alumnos", conn)

    id                     nombre  edad         ciudad
0    1                        Ana    22         Bogotá
1    2                       Luis    24       Medellín
2    3                      Marta    23           Cali
3    4                      Pedro    22         Bogotá
4    5                   Cristian    27         Bogotá
5    6              Brayan posada    31         Bogota
6    7                      Joan     22         Bogotá
7    8  Diego Andres Paez Menjura    19  Villavicencio
8    9                     Danilo    32       Medellin
9   10             Faber Grisales    27         Bogotá
10  11                    MICHAEL    37         SOACHA

In [36]:
consulta.groupby('ciudad').count()

               id  nombre  edad
ciudad
Bogota          1       1     1
Bogotá          5       5     5
Cali            1       1     1
Medellin        1       1     1
Medellín        1       1     1
SOACHA          1       1     1
Villavicencio   1       1     1

In [38]:
pd.read_sql_query("SELECT ciudad, count(id) FROM alumnos group by ciudad", conn)

/tmp/ipython-input-247916731.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT ciudad, count(id) FROM alumnos group by ciudad", conn)

          ciudad
0         Bogota  1
1         Bogotá  5
2           Cali  1
3       Medellin  1
4       Medellín  1
5         SOACHA  1
6  Villavicencio  1

In [48]:
consulta = pd.read_sql_query("SELECT * FROM alumnos", conn)
consulta

/tmp/ipython-input-3685748699.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  consulta = pd.read_sql_query("SELECT * FROM alumnos", conn)

   id          nombre  edad    ciudad
0   5        Cristian    27    Bogotá
1   6   Brayan posada    31    Bogota
2   9          Danilo    32  Medellin
3  10  Faber Grisales    27    Bogotá
4  11         MICHAEL    37    SOACHA

In [47]:
cur.execute('''
DELETE alumnos
WHERE edad < 25
''')

In [54]:
consulta = pd.read_sql_query("SELECT Ciudad, Count(*) FROM alumnos GROUP BY Ciudad HAVING count(*) = 5", conn)
consulta

/tmp/ipython-input-3790679471.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  consulta = pd.read_sql_query("SELECT Ciudad, Count(*) FROM alumnos GROUP BY Ciudad HAVING count(*) = 5", conn)

   Ciudad
0  Bogotá  5

In [56]:
consulta = pd.read_sql_query("SELECT TOP 5 * FROM alumnos ORDER BY nombre", conn)
consulta

/tmp/ipython-input-3723116381.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  consulta = pd.read_sql_query("SELECT TOP 5 * FROM alumnos ORDER BY nombre", conn)

   id                     nombre  edad         ciudad
0   1                        Ana    22         Bogotá
1   6              Brayan posada    31         Bogota
2   5                   Cristian    27         Bogotá
3   9                     Danilo    32       Medellin
4   8  Diego Andres Paez Menjura    19  Villavicencio